name: flutter_latihan_responsive
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  moor_flutter: 4.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  moor_generator: 4.6.0+1
  build_runner: 2.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
