name: flutter_latihan_responsive
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  hive: 2.2.3
  hive_flutter: 1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  hive_generator: 1.1.3
  build_runner: 2.2.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
